image:
  name: kpassapk/ufm-structs
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
pipelines:
  default:
    - step:
        script:
          - cs22 test 0_0_hello_world
